dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-05/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: lfUHrXIXIs4QFM4Faj/cZqQIfnYsmuBwi6xLUc/HQdXRWrBWuCog9hBIVbeLU8HaPO/D2C5z62xoZrdIAONQf+zv+jlFC7njZKAObfE+M5zznuuu5Tkmwa/XKRiBTJvjaQCl2UIV4hEgOHpWUw+nC0fg9ktbaSmzo2q3LDwLzdZz2lHTfFAPmlQyT4s+4L464dfZDjSit1Mp2GIzP/sq7r9VJLTamm8+lxeu7mym/7PopshfB4A6hYvgfLqN7d8O0byV+/Z7ukRDDEjkZnnDtsSLZnMeU9huQSCZ7lRdqT4ne6zq+g2MVs61FfuvCLDdkoviYrvtF6OPTZ+2dZyr1mPfCArv8kdJHlfuWLaRGJP9G577JLyLuGQlUgcm6T7Xoe7rKQrDB/SaMcG/fsZYnYE1jsVTazLZBx2wRckYhWP7Rh6taxdQEkaHTNW3NAChklm7VInUWo/s6GP4TxIbrC6gKKrfkl2Za1PBQkZtGcXrpntJbVaCM7BZzk1rhsN9CNWJRiLjggap0UDnnmUFDdjDchsOWgvwP4yiy5/pCFRZ1/FYvCnBid3+1M5z8MrP/RhlTpAIsyNLLt8oVe89BXX27mt6wiWUEqAMIaLlOOv1vuv8vzlDMZp/DrlRdtrJsLNWx2s4D4PA4/Cbps8oeIosaxulvqrLZcG0YlulrkI=
